### ISSUE TITLE
[Can or Cannot multiple FETCH JOIN] 테스트케이스 작성시 에러내부 메시지 확인 어떻게 하셨나요?

### ISSUE THREAD

**Issue by miimmin** [Spring-Issue-solving/All-Spring-Issues#11]
Mulitple Fetch Join 으로 인한 오류는
org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.loader.MultipleBagFetchException
이런식으로 나오는것을 확인할 수 있었습니다.

에러의 이런 구조를 뭐라고 정의하는지,
즉, 내부에 메시지를 가지고 있다던가, 혹은 계층적으로 이루어진 구조라던가 저렇게 에러가 이어진 것을 어떻게 명명하는지가 궁금합니다

추가로 해당 에러인 MultipleBagFetchException 에러 확인을 AssertJ 등 테스트 프레임워크에서 어떤 함수를 써서 확인하셨는지 궁금합니다!

**Comment by Yiseull** [comment]
InvalidDataAccessApiUsageException의 Root Cause가 MultipleBagFetchException 입니다. 

InvalidDataAccessApiUsageException가 발생하면 Error Message에 예외의 근본 원인인 MultipleBagFetchException이 들어있고, 저는 그것을 이용하여 아래와 같이 MultipleBagFetchException이 발생한 것을 확인하였습니다.

```
assertThatThrownBy(() -> bandRepository.findAllWithFetchJoin())
                .isInstanceOf(InvalidDataAccessApiUsageException.class)
                .hasMessageContaining("MultipleBagFetchException");
```

**Comment by Yiseull** [comment]
Root Cause를 hasMessageContaining 메서드가 아닌 직접적으로 체크하는 방법을 찾아보았습니다.

hasRootCauseInstanceOf 메서드 를 통해 발생 예외의 Root Cause를 체크할 수 있습니다. 아래 코드는 이 메서드를 사용하여  MultipleBagFetchException을 체크하는 코드입니다.

```
assertThatThrownBy(() -> bandRepository.findAllWithFetchJoin())
                .hasRootCauseInstanceOf(MultipleBagFetchException.class)
                .hasMessageContaining("cannot simultaneously fetch multiple bags");
```
