### ISSUE TITLE
[JPA-DirtyChecking Performance] Dirty Checking 성능 체크 시 테스트 코드에서 H2 DB를 선택하신 이유가 있나요?

### ISSUE THREAD

**Issue by Yiseull** [Spring-Issue-solving/All-Spring-Issues#12]
H2 데이터베이스를 선택하신 이유가 있는지 궁금합니다. 

MySQL을 사용한 Test에서는 @Transactional(readOnly = true)을 사용할 수 없다고 하셨는데, 왜 사용할 수 없는지도 궁금합니다!

**Comment by miimmin** [comment]
` @transactional(readOnly = true) `옵션을 사용하게 되면 트랜잭션을 조회용도로만 사용합니다
조회용이 아닌 트랜잭션에서 해당 옵션을 사용하면 
`java.sql.SQLException: Connection is read-only. Queries leading to data modification are not allowed` 에러를 발생시킵니다

해당 에러는 말그대로 조회용 트랜잭션에서 수정쿼리가 발생했다는 의미로
본 테스트에서 테스트검증코드에는 Update 쿼리가 없으나 @Before 로 테스트할 데이터를 만들어주는 단계에서 디비에 Insert 쿼리가 발생하기 때문에 해당 에러가 발생하게 됩니다.

좋은 질문 주셔서 H2로 한 테스트가 잘못된 것을 알게됐습니다
H2에서 에러가 발생하지 않는 이유는 H2의 JdbcConnection이 setReadOnly를 무시하도록 내부구현 되어있기 때문입니다.
따라서 H2로 실행한 테스트는 잘못 설계된 테스트입니다.
