### ISSUE TITLE
[N+1 Query Problem] QueryDSL이 무엇이고, 언제 사용하나요?

### ISSUE THREAD

**Issue by Yiseull** [Spring-Issue-solving/All-Spring-Issues#3]

**Comment by miimmin** [comment]
QueryDSL 은 SQL, JPQL 등을 자바코드로 작성할 수 있도록 해주는 빌더 오픈소스 프레임워크 입니다.

**Comment by miimmin** [comment]
QueryDSL 은 SQL, JPQL 등을 자바코드로 작성할 수 있도록 해주는 빌더 오픈소스 프레임워크 입니다.
정적타입을 이용하여 하이버네이트 쿼리 언어(HQL: Hibernate Query Language)의 쿼리를 타입에 안전하게 생성 및 관리해주는 용도로 사용하며,

**Comment by miimmin** [comment]
QueryDSL 은 SQL, JPQL 등을 자바코드로 작성할 수 있도록 해주는 빌더 오픈소스 프레임워크 입니다.
정적타입을 이용하여 하이버네이트 쿼리 언어(HQL: Hibernate Query Language)의 쿼리를 Type-Safey하게 생성, 관리하는 용도로 사용하며,
복잡한 쿼리와 동적쿼리를 쉽게 작성할 수 있다는 장점을 가지고 있습니다

추가로 학습하시는데 도움이 될만한 공식 레포 첨부합니다
Reference
공식문서: http://querydsl.com
깃 레포지토리: https://github.com/querydsl/querydsl/tree/master/querydsl-jpa
