### ISSUE TITLE
[N+1 Query Problem] 지연로딩전략에서 N+1 발생을 위해 EntityManager.refresh()를 사용하신 이유가 궁금합니다

### ISSUE THREAD

**Issue by miimmin** [Spring-Issue-solving/All-Spring-Issues#4]

**Comment by Yiseull** [comment]
지연로딩 전략에서 N+1이 발생하지 않고 Artist.getSongs()이 null이 발생하였습니다. 이러한 결과가 일어난 이유로 Artist가 아직 로드되지 않았기 때문이라고 생각하였고, Artist가 로드되면 null 이슈가 해결되고 N+1 도 발생할 것이라고 짐작하였습니다. 
그래서 Artist를 직접 로드시키기 위해서 EntityManager.refresh()를 사용하였고, 해당 방법으로 문제를 해결할 수 없었습니다.

이 문제의 해결 방법은 EntityManager.clear()를 사용하는 것 입니다. 


추가로 EntityManager.refresh() 메서드 설명을 하자면, 이 메소드는 현재 영속성 컨텍스트에 있는 엔티티의 상태를 데이터베이스에서 새로 가져와 업데이트합니다. 예를 들어, 특정 엔티티의 변경 내용을 롤백하고 싶을 때나, 다른 트랜잭션에서 해당 엔티티를 수정한 경우에 refresh() 메서드를 사용하여 최신 데이터로 엔티티를 갱신할 수 있습니다.
