### ISSUE TITLE
[N+1 Query Problem] N+1 발생 여부 판단으로 Query Log를 찍어서 확인하는 방법 말고 로직으로 확인하는 등 다른 방법은 없을까요?

### ISSUE THREAD

**Issue by Yiseull** [Spring-Issue-solving/All-Spring-Issues#6]

**Comment by miimmin** [comment]
Hibernate의 StatementInspector 인터페이스를 구현하면 쿼리문을 가로채어 원하는 로직, 이를테면 언급된 '쿼리를 카운팅'하는 등의 로직을 구현할 수 있습니다.
자세한 코드는 pull-request 하여, merge가 된다면 확인가능합니다.
